/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    members: Member;
    faq: Faq;
    media: Media;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Wijzig je dit na publicatie? Maak dan een redirect aan.
   */
  slug: string;
  /**
   * Sleep blokken om de volgorde van de pagina te wijzigen.
   */
  layout?:
    | (
        | HeroBlock
        | RichTextBlockType
        | SplitContentBlock
        | CtaBannerBlock
        | CardGridBlock
        | MediaBlockType
        | GalleryBlock
        | FaqBlockType
        | EventListBlock
        | NextEventBlock
        | MemberGridBlock
        | FormBlockType
        | LogoStripBlock
        | MapBlockType
        | SeparatorBlockType
      )[]
    | null;
  /**
   * Leeg laten om de standaardfoto uit de instellingen te gebruiken.
   */
  footerImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('full' | 'compact') | null;
  /**
   * Framing stel je in op de foto zelf (velden Focus X/Y in de mediabibliotheek).
   */
  image: number | Media;
  /**
   * Regeleindes worden overgenomen.
   */
  title: string;
  subtitle?: string | null;
  /**
   * Aanzetten als de tekst slecht leesbaar is.
   */
  overlay?: boolean | null;
  showScrollHint?: boolean | null;
  buttons?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external' | 'anchor') | null;
          page?: (number | null) | Page;
          url?: string | null;
          /**
           * Bijvoorbeeld: contact
           */
          anchor?: string | null;
          newTab?: boolean | null;
          style?: ('primary' | 'secondary' | 'ghost') | null;
        };
        id?: string | null;
      }[]
    | null;
  separatorColor?: ('dark' | 'red' | 'white' | 'blue') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijf wat er te zien is, voor schermlezers en Google. Puur decoratief? Zet een spatie.
   */
  alt: string;
  /**
   * 0 = links, 100 = rechts.
   */
  focusX?: number | null;
  /**
   * 0 = boven, 100 = onder.
   */
  focusY?: number | null;
  credit?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType".
 */
export interface RichTextBlockType {
  /**
   * Klein groen kopje boven de tekst.
   */
  eyebrow?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('narrow' | 'wide') | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock".
 */
export interface SplitContentBlock {
  mediaType?: ('image' | 'statement') | null;
  image?: (number | null) | Media;
  /**
   * Kort houden — dit wordt heel groot weergegeven.
   */
  statement?: string | null;
  eyebrow?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  button?: {
    link?: {
      /**
       * Leeg laten als je hier geen knop wilt.
       */
      label?: string | null;
      type?: ('internal' | 'external' | 'anchor') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * Bijvoorbeeld: contact
       */
      anchor?: string | null;
      newTab?: boolean | null;
      style?: ('primary' | 'secondary' | 'ghost') | null;
    };
  };
  mediaPosition?: ('right' | 'left') | null;
  framed?: boolean | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  title?: string | null;
  body?: string | null;
  buttons: {
    link: {
      label: string;
      type?: ('internal' | 'external' | 'anchor') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * Bijvoorbeeld: contact
       */
      anchor?: string | null;
      newTab?: boolean | null;
      style?: ('primary' | 'secondary' | 'ghost') | null;
    };
    id?: string | null;
  }[];
  layout?: ('center' | 'row' | 'stack') | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  title?: string | null;
  columns?: ('2' | '3' | '4') | null;
  cards: {
    emoji?: string | null;
    title: string;
    /**
     * Alleen invullen bij tickets.
     */
    price?: string | null;
    image?: (number | null) | Media;
    body?: string | null;
    button?: {
      link?: {
        /**
         * Leeg laten als je hier geen knop wilt.
         */
        label?: string | null;
        type?: ('internal' | 'external' | 'anchor') | null;
        page?: (number | null) | Page;
        url?: string | null;
        /**
         * Bijvoorbeeld: contact
         */
        anchor?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary' | 'ghost') | null;
      };
    };
    id?: string | null;
  }[];
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  kind?: ('image' | 'video') | null;
  image?: (number | null) | Media;
  /**
   * De embed-URL, bijvoorbeeld van Mux of YouTube.
   */
  videoUrl?: string | null;
  /**
   * Verplicht voor schermlezers.
   */
  videoTitle?: string | null;
  fullBleed?: boolean | null;
  caption?: string | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  title?: string | null;
  images: (number | Media)[];
  layout?: ('scroll' | 'grid') | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlockType".
 */
export interface FaqBlockType {
  title?: string | null;
  source?: ('all' | 'selected') | null;
  items?: (number | Faq)[] | null;
  /**
   * Leeg laten voor volle breedte.
   */
  image?: (number | null) | Media;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * Vragen die op de site getoond worden. Sorteren gaat op volgnummer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock".
 */
export interface EventListBlock {
  title?: string | null;
  intro?: string | null;
  filter?: ('upcoming' | 'past' | 'all') | null;
  /**
   * 0 = geen limiet.
   */
  limit?: number | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextEventBlock".
 */
export interface NextEventBlock {
  eyebrow?: string | null;
  /**
   * Aan het eind van het seizoen staat er niets in de agenda. Dan toont dit blok deze tekst, in plaats van van de pagina te verdwijnen.
   */
  emptyText: string;
  /**
   * Gebruikt wanneer de rit zelf geen foto heeft, en bij de terugvaltekst.
   */
  image?: (number | null) | Media;
  button?: {
    link?: {
      /**
       * Leeg laten als je hier geen knop wilt.
       */
      label?: string | null;
      type?: ('internal' | 'external' | 'anchor') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * Bijvoorbeeld: contact
       */
      anchor?: string | null;
      newTab?: boolean | null;
      style?: ('primary' | 'secondary' | 'ghost') | null;
    };
  };
  mediaPosition?: ('right' | 'left') | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'nextEvent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MemberGridBlock".
 */
export interface MemberGridBlock {
  title?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ankerlinks naar elk lid bovenaan het blok.
   */
  showIndex?: boolean | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'memberGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType".
 */
export interface FormBlockType {
  form: number | Form;
  title?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Verplicht bij formulieren die persoonsgegevens verzamelen (AVG). Verwijs naar de privacyverklaring.
   */
  privacyNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock".
 */
export interface LogoStripBlock {
  title?: string | null;
  logos: {
    logo: number | Media;
    link?: {
      /**
       * Leeg laten als je hier geen knop wilt.
       */
      label?: string | null;
      type?: ('internal' | 'external' | 'anchor') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * Bijvoorbeeld: contact
       */
      anchor?: string | null;
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlockType".
 */
export interface MapBlockType {
  title?: string | null;
  placeName: string;
  address?: string | null;
  /**
   * Bijvoorbeeld 51.4637
   */
  latitude: number;
  /**
   * Bijvoorbeeld 4.4637
   */
  longitude: number;
  zoom?: number | null;
  /**
   * Achtergrond en ruimte rond dit blok.
   */
  appearance?: {
    background?: ('dark' | 'red' | 'white' | 'blue' | 'none') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    separatorTop?: boolean | null;
    separatorBottom?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeparatorBlockType".
 */
export interface SeparatorBlockType {
  color?: ('dark' | 'red' | 'white' | 'blue') | null;
  position?: ('top' | 'bottom') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'separator';
}
/**
 * Clubritten, weekenden en evenementen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  /**
   * Alleen invullen bij meerdaagse ritten of weekenden.
   */
  endDate?: string | null;
  location?: string | null;
  /**
   * Een of twee zinnen. Verschijnt in de agendalijst.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Optioneel, bijvoorbeeld een inschrijfformulier.
   */
  signupUrl?: string | null;
  archiveAfter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * Wordt het anker op de spotlightpagina.
   */
  slug: string;
  images?: (number | Media)[] | null;
  story: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Redacteuren beheren content. Beheerders beheren ook gebruikers en instellingen.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Oude URL naar nieuwe URL. Vul hier de WordPress-paden in zodat bestaande links blijven werken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockTypeSelect<T>;
        splitContent?: T | SplitContentBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        mediaBlock?: T | MediaBlockTypeSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        faqBlock?: T | FaqBlockTypeSelect<T>;
        eventList?: T | EventListBlockSelect<T>;
        nextEvent?: T | NextEventBlockSelect<T>;
        memberGrid?: T | MemberGridBlockSelect<T>;
        formBlock?: T | FormBlockTypeSelect<T>;
        logoStrip?: T | LogoStripBlockSelect<T>;
        mapBlock?: T | MapBlockTypeSelect<T>;
        separator?: T | SeparatorBlockTypeSelect<T>;
      };
  footerImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  image?: T;
  title?: T;
  subtitle?: T;
  overlay?: T;
  showScrollHint?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
              style?: T;
            };
        id?: T;
      };
  separatorColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType_select".
 */
export interface RichTextBlockTypeSelect<T extends boolean = true> {
  eyebrow?: T;
  content?: T;
  width?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock_select".
 */
export interface SplitContentBlockSelect<T extends boolean = true> {
  mediaType?: T;
  image?: T;
  statement?: T;
  eyebrow?: T;
  content?: T;
  button?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
              style?: T;
            };
      };
  mediaPosition?: T;
  framed?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
              style?: T;
            };
        id?: T;
      };
  layout?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  title?: T;
  columns?: T;
  cards?:
    | T
    | {
        emoji?: T;
        title?: T;
        price?: T;
        image?: T;
        body?: T;
        button?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                    style?: T;
                  };
            };
        id?: T;
      };
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType_select".
 */
export interface MediaBlockTypeSelect<T extends boolean = true> {
  kind?: T;
  image?: T;
  videoUrl?: T;
  videoTitle?: T;
  fullBleed?: T;
  caption?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  images?: T;
  layout?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlockType_select".
 */
export interface FaqBlockTypeSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  items?: T;
  image?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock_select".
 */
export interface EventListBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  filter?: T;
  limit?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextEventBlock_select".
 */
export interface NextEventBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  emptyText?: T;
  image?: T;
  button?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
              style?: T;
            };
      };
  mediaPosition?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MemberGridBlock_select".
 */
export interface MemberGridBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  showIndex?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType_select".
 */
export interface FormBlockTypeSelect<T extends boolean = true> {
  form?: T;
  title?: T;
  intro?: T;
  privacyNote?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock_select".
 */
export interface LogoStripBlockSelect<T extends boolean = true> {
  title?: T;
  logos?:
    | T
    | {
        logo?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlockType_select".
 */
export interface MapBlockTypeSelect<T extends boolean = true> {
  title?: T;
  placeName?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  zoom?: T;
  appearance?:
    | T
    | {
        background?: T;
        padding?: T;
        separatorTop?: T;
        separatorBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeparatorBlockType_select".
 */
export interface SeparatorBlockTypeSelect<T extends boolean = true> {
  color?: T;
  position?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  summary?: T;
  description?: T;
  image?: T;
  signupUrl?: T;
  archiveAfter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  images?: T;
  story?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  focusX?: T;
  focusY?: T;
  credit?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Het hoofdmenu, op desktop en mobiel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  items?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external' | 'anchor') | null;
          page?: (number | null) | Page;
          url?: string | null;
          /**
           * Bijvoorbeeld: contact
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  cta: {
    link: {
      label: string;
      type?: ('internal' | 'external' | 'anchor') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * Bijvoorbeeld: contact
       */
      anchor?: string | null;
      newTab?: boolean | null;
      style?: ('primary' | 'secondary' | 'ghost') | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Pagina's kunnen dit overschrijven.
   */
  backgroundImage?: (number | null) | Media;
  items?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external' | 'anchor') | null;
          page?: (number | null) | Page;
          url?: string | null;
          /**
           * Bijvoorbeeld: contact
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Privacyverklaring, voorwaarden. Verplicht zodra je formulieren persoonsgegevens verzamelen.
   */
  legalItems?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external' | 'anchor') | null;
          page?: (number | null) | Page;
          url?: string | null;
          /**
           * Bijvoorbeeld: contact
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Gegevens die op elke pagina terugkomen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Wordt gebruikt als een pagina zelf geen deelafbeelding heeft ingesteld.
   */
  defaultOgImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  email?: string | null;
  areaServed?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'strava' | 'untappd' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
              style?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  backgroundImage?: T;
  items?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  legalItems?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultOgImage?: T;
  logo?: T;
  email?: T;
  areaServed?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}